### PR TITLE
(Suggestion) Throw Warnings as Errors

### PR DESCRIPTION
**Pull request by aang114**

### CODE REVIEW

**Comment by alebaffa** [comment]
Is this after a discussion with Gio?

**Comment by aang114** [comment]
> Is this after a discussion with Gio?

Yeah. But he's not sure if we should throw warnings as errors. What do you think?

**Comment by alebaffa** [comment]
Some times it happens that some warnings might be necessary to keep. It's not our case now, but I generally prefer to have an internal policy for warnings instead of raising errors in compilation.

**Comment by aang114** [comment]
> Some times it happens that some warnings might be necessary to keep. It's not our case now, but I generally prefer to have an internal policy for warnings instead of raising errors in compilation.

Okay sure, makes sense. So should close this PR (without merging) @sinkingsugar ?

**Pull request closed without merging**
