### PR TITLE
Refactored `exclude_tags` param of `GetProtosParams`

### PR DESCRIPTION
**Pull request by aang114**

### CODE REVIEW

**Review by alebaffa — APPROVED** [review]

**Comment by alebaffa** [comment]
@aang114 Do you mind create tests that cover the new parts? Otherwise having introduced this code coverage tool is pretty useless 😄

**Review by alebaffa — CHANGES_REQUESTED** [review]
@aang114 Do you mind creating tests that cover the new parts? Otherwise having introduced this code coverage tool is pretty useless 😄

**Comment by sinkingsugar** [comment]
@aang114 can we finish this one?

**Comment by aang114** [comment]
> @aang114 Do you mind creating tests that cover the new parts? Otherwise having introduced this code coverage tool is pretty useless 😄

Done (and thanks to the the test case, I actually found a bug 😂). Could you re-approve this PR? Thanks

**Review by alebaffa — APPROVED** [review]

**Pull request merged**
