### PR TITLE
Added RPC `protos.getGenealogy()`

### PR DESCRIPTION
**Pull request by aang114**

### CODE REVIEW

**Comment by alebaffa** [comment]
@aang114  What's the status of this one?

**Comment by aang114** [comment]
> @aang114 What's the status of this one?

I want merge this after #148 is merged

**Comment by paulinechi** [comment]
Could you update https://github.com/fragcolor-xyz/clamor/blob/add-rpc-getGenealogy/rpc/index.js to include getGenealogy too? Thanks :)

**Review by alebaffa — CHANGES_REQUESTED** [review]
Please, take care of Pauline's request

**Comment by aang114** [comment]
> Could you update https://github.com/fragcolor-xyz/clamor/blob/add-rpc-getGenealogy/rpc/index.js to include getGenealogy too? Thanks :)

Done.

**Review by alebaffa — APPROVED** [review]

**Pull request merged**
