### PR TITLE
CI Throws Error If Any Public Function/Struct/Enum/Module is Not Documented

### PR DESCRIPTION
**Pull request by aang114**
Note: Crate-Level Documentation is the documentation added to the first few lines of the `lib.rs` file of the Crate

### CODE REVIEW

**Comment by alebaffa** [comment]
Is this after a discussion?

**Comment by aang114** [comment]
> Is this after a discussion?

I just found this online and thought: "why not?". what do you think 😅 ?

**Comment by alebaffa** [comment]
Well, this could make sense. Even if, same as warnings, I generally prefer to have an internal policy about documentation..but this could make more sense.

**Comment by alebaffa** [comment]
Probably, though, you may want to run this new build locally and see what are the missing docs...and then update the PR with all the missing ones too.

**Comment by aang114** [comment]
This will force us to write documentation for any extrinsic / public function that we add - otherwise the CI fails! So hopefully this reduces any time spent asking each other about a particular function/extrinsic/etc

**Comment by sinkingsugar** [comment]
> This will force us to write documentation for any extrinsic / public function that we add - otherwise the CI fails! So hopefully this reduces any time spent asking each other about a particular function/extrinsic/etc

title is misleading if this is the case.. which is annoying

**Comment by aang114** [comment]
> > This will force us to write documentation for any extrinsic / public function that we add - otherwise the CI fails! So hopefully this reduces any time spent asking each other about a particular function/extrinsic/etc
> 
> title is misleading if this is the case.. which is annoying

Title has been changed

**Review by alebaffa — APPROVED** [review]

**Pull request merged**
